### ISSUE TITLE
Read members from YAML or other machine-readable format, generate HTML

### ISSUE THREAD

**Issue by mgielda** [chipsalliance/chips-alliance-website#16]
Currently the members list is implemented as shortcodes, which is definitely not how we'd like this - we want automation which would enable us to automatically process the membership list etc. So, We would need the HTML from here:

https://github.com/chipsalliance/chips-alliance-website/blob/7c9a2b29704085651fd02594ec104c2fb741dc88/layouts/shortcodes/members.html

To instead be generated from a YAML (.yml) file, most likely to be put in the data/ directory. That would also of course eliminate repetition in the code and separate content from presentation.

Let me know if that is clear or I need to provide more details.

**Comment by cjyabraham** [comment]
Is this the format you're expecting?

```
members:
  - member:
    name: AMD
    url: https://www.amd.com/en
    image: amd.svg
    level: platinum
  - member:
    name: Alibaba
    url: https://www.alibabagroup.com/
    image: alibaba.png
    level: platinum
  - member:
    name: Antmicro
    url: https://antmicro.com/
    image: antmicro.png
    level: platinum
```
